### ISSUE TITLE
Feedstock building on TravisCI anyways

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyagrum-feedstock#3]
Not sure what the issue is here, but we seem to be getting builds on Travis CI when we shouldn't. Have raised issue ( https://github.com/travis-ci/travis-ci/issues/6710 ) upstream to try and get to the bottom of this.

cc @pelson

**Comment by jakirkham** [comment]
These are being enabled in the PR ( https://github.com/conda-forge/pyagrum-feedstock/pull/2 ). Sorry for the noise. Closing.

**Comment by jschueller** [comment]
no problem
